blank_issues_enabled: false
#contact_links:
#  - name: â‰ï¸ Need help with Node.js?
#    url: https://github.com/nodejs/help
#    about: Please file an issue in our help repo.
#  - name: ğŸŒ Found a problem with example.com?
#    url: https://github.com/bolthur/bolthur.github.io/issues/new/choose
#    about: Please file an issue in the bolthur website repo.
